### ISSUE TITLE
Is it possible to install node.js in HP.UX?

### ISSUE THREAD

**Issue by hyoungwoo-kim** [playnodeconf/ama#10]

**Comment by daclouds** [comment]
HP-UX is not officially supported.
https://nodejs.org/en/download/

**Comment by hyoungwoo-kim** [comment]
안녕하세요. 김형우라고 합니다.
보내주신 답변은 잘 받았습니다.
그렇다면, ​어떤 설치파일을 다운받아서 테스트라도 해 볼 수 있을까요?



================================================

감사합니다. Have a good day!!!!!!!!!!!!


| Mobile. 010-2684-7346 | Email. hwkim00@ <lbw92@kwic.co.kr>gmail.com





2016-04-18 16:57 GMT+09:00 Jongil Seok <notifications@github.com>:

**Comment by daclouds** [comment]
You can try from source.
https://github.com/nodejs/node/blob/master/BUILDING.md

**Comment by hyoungwoo-kim** [comment]
답변 감사합니다.
즐거운 저녁시간 되시기 바랍니다.

감사합니다.


================================================

감사합니다. Have a good day!!!!!!!!!!!!


| Mobile. 010-2684-7346 | Email. hwkim00@ <lbw92@kwic.co.kr>gmail.com





2016-04-18 18:02 GMT+09:00 Jongil Seok <notifications@github.com>:
