### ISSUE TITLE
올해는 play.node 컨퍼런스가 없나요?

### ISSUE THREAD

**Issue by charonfly** [playnodeconf/ama#11]
안녕하세요.

올해는 play.node 컨퍼런스가 없는건가요?
작년에 참석해서 유익한 시간 되어서 여쭤봅니다.

답변 부탁 드립니다.
감사합니다.

**Comment by outsideris** [comment]
@charonfly 안녕하세요. 관심가져 주셔서 감사합니다.
아직 자세한 내용을 말씀드리기 어렵지만 올해도 play.node를 열어보려고 노력하고 있습니다. 
상세 일정 등이 결정되는대로 별도의 채널을 통해서 공지하도록 하겠습니다.
