### ISSUE TITLE
IBM에서 보낸 등록확인메일 인코딩 깨짐 (ISO-2022-KR)

### ISSUE THREAD

**Issue by feminie** [playnodeconf/ama#12]
안녕하세요

playnode 2016 참가등록을 IBM등록 폼에서 완료했습니다.
등록확인을 이메일로 받았는데 인코딩문제로 인해 메일 내용확인이 되질 않습니다.

작년에는 참가비를 결제해야 했었는데
올해는 참가비 결제가 필요없는 것인가요?

문제가 발생한 이메일 소스는 아래와 같습니다.
`From - Mon Nov 07 13:20:50 2016
X-Account-Key: account1
X-UIDL: d6361412163656719881814423036
X-Mozilla-Status: 1001
X-Mozilla-Status2: 00000000
X-Mozilla-Keys:                                                                                 
x-sender: hykoh@kr.ibm.com
x-newtrunsreceiver: shincm@mirero.co.kr
Received: from mx0a-001b2d01.pphosted.com (148.163.156.1)
	by GROUPWARE with SMTP; Mon, 07 Nov 2016 13:20:36  +0900 (KST)
Received: from pps.filterd (m0098393.ppops.net [127.0.0.1])
	by mx0a-001b2d01.pphosted.com (8.16.0.17/8.16.0.17) with SMTP id uA74If05102991
	for <shincm@mirero.co.kr>; Sun, 6 Nov 2016 23:20:25 -0500
Received: from e37.co.us.ibm.com (e37.co.us.ibm.com [32.97.110.158])
	by mx0a-001b2d01.pphosted.com with ESMTP id 26j6v3pj7m-1
	(version=TLSv1.2 cipher=AES256-SHA bits=256 verify=NOT)
	for <shincm@mirero.co.kr>; Sun, 06 Nov 2016 23:20:25 -0500
Received: from localhost
	by e37.co.us.ibm.com with IBM ESMTP SMTP Gateway: Authorized Use Only! Violators will be prosecuted
	for <shincm@mirero.co.kr> from <hykoh@kr.ibm.com>;
	Sun, 6 Nov 2016 21:20:24 -0700
Received: from d03dlp03.boulder.ibm.com (9.17.202.179)
	by e37.co.us.ibm.com (192.168.1.137) with IBM ESMTP SMTP Gateway: Authorized Use Only! Violators will be prosecuted;
	Sun, 6 Nov 2016 21:20:21 -0700
Received: from b01cxnp23032.gho.pok.ibm.com (b01cxnp23032.gho.pok.ibm.com [9.57.198.27])
	by d03dlp03.boulder.ibm.com (Postfix) with ESMTP id 357EB19D801C
	for <shincm@mirero.co.kr>; Sun,  6 Nov 2016 21:19:44 -0700 (MST)
Received: from b01ledav006.gho.pok.ibm.com (b01ledav006.gho.pok.ibm.com [9.57.199.111])
	by b01cxnp23032.gho.pok.ibm.com (8.14.9/8.14.9/NCO v10.0) with ESMTP id uA74KImV13435282
	for <shincm@mirero.co.kr>; Mon, 7 Nov 2016 04:20:20 GMT
Received: from b01ledav006.gho.pok.ibm.com (unknown [127.0.0.1])
	by IMSVA (Postfix) with ESMTP id 2BAAEAC058
	for <shincm@mirero.co.kr>; Sun,  6 Nov 2016 23:20:20 -0500 (EST)
Received: from g01aedsmtp001.ahe.pok.ibm.com (unknown [9.57.170.42])
	by b01ledav006.gho.pok.ibm.com (Postfix) with ESMTPS id 15AD1AC04A
	for <shincm@mirero.co.kr>; Sun,  6 Nov 2016 23:20:20 -0500 (EST)
Received: from g01acxdb603.ahe.pok.ibm.com (g03edndreturn001.ahe.boulder.ibm.com [9.17.247.205])
	by g01aedsmtp001.ahe.pok.ibm.com (8.15.1/8.14.7/NCO v10.0) with ESMTP id uA74KJ5X12124390
	for <shincm@mirero.co.kr>; Mon, 7 Nov 2016 05:20:19 +0100
Date: Sun, 6 Nov 2016 23:20:19 -0500
From: hykoh@kr.ibm.com
Reply-To: hykoh@kr.ibm.com
To: shincm@mirero.co.kr
Subject: =?EUC-KR?B?te63zyDIrsDOIDogSUJNIERldmVsb3BlckNvbm5lY3QgKyBwbGF5Lm5vZGU=?=
 =?EUC-KR?B?IDIwMTYgLSBTZW91bA==?=
X-MIMETrack: Serialize by Router on G01ACXDB603/01/A/IBMEXT(Release 9.0.1FP5HF142 | January
 21, 2016) at 11/06/2016 23:20:19
MIME-Version: 1.0
Content-type: multipart/alternative; 
	Boundary="0__=0ABB0AF7DF8452638f9e8a93df938690918c0ABB0AF7DF845263"
Content-Disposition: inline
X-TM-AS-GCONF: 00
X-Content-Scanned: Fidelis XPS MAILER
x-cbid: 16110704-0024-0000-0000-000014F2D5F1
X-IBM-SpamModules-Scores: 
X-IBM-SpamModules-Versions: BY=3.00006035; HX=3.00000240; KW=3.00000007;
 PH=3.00000004; SC=3.00000189; SDB=6.00777541; UDB=6.00374351; IPR=6.00554843;
 BA=6.00004857; NDR=6.00000001; ZLA=6.00000005; ZF=6.00000009; ZB=6.00000000;
 ZP=6.00000000; ZH=6.00000000; ZU=6.00000002; MB=3.00013221; XFM=3.00000011;
 UTC=2016-11-07 04:20:22
X-IBM-AV-DETECTION: SAVI=unused REMOTE=unused XFE=unused
x-cbparentid: 16110704-0025-0000-0000-000045E9F989
Message-Id: <OF3D645612.5ED8C21C-ON85258064.0017D4F3@us.ibm.com>
X-Proofpoint-Virus-Version: vendor=fsecure engine=2.50.10432:,, definitions=2016-11-07_01:,,
 signatures=0
X-Proofpoint-Spam-Details: rule=outbound_notspam policy=outbound score=0 spamscore=0 suspectscore=3
 malwarescore=0 phishscore=0 adultscore=0 bulkscore=0 classifier=spam
 adjust=0 reason=mlx scancount=1 engine=8.0.1-1609300000
 definitions=main-1611070081

--0__=0ABB0AF7DF8452638f9e8a93df938690918c0ABB0AF7DF845263
Content-type: text/plain; charset=ISO-2022-KR

$)C
. =EC69N  4T

IBM DeveloperConnect + play.node 2016?!  Seoul?!<- GO4B 2016?y 11?y 23@O?!
5n7OGXAV<E<- 0(;gGU4O4Y. @L:%F. 5n7O@L ?O7a5G>z=@4O4Y.

>F7!  3;?k@; H.@NGXAV=C1b 9Y6x4O4Y. 88>`, 3;?k?! <vA$ ;gGW@L GJ?dGO0E3*, Az
9.@L @V@8=C8i, hykoh@kr.ibm.com7N 8^@O@; AV=C1b 9Y6x4O4Y.

5n7O@Z8m 	. =EC69N  4T

@e<R 		Ritz Carlton Hotel Seoul
		<-?o=C 0-3218 :@@:;g7N 120
		Seoul

3/B%		2016?y 11?y 23@O

@L9x G`;g?!<- :I <v @V1f 9Y6x4O4Y.

IBM
--0__=0ABB0AF7DF8452638f9e8a93df938690918c0ABB0AF7DF845263
Content-type: text/html; charset=ISO-2022-KR
Content-Disposition: inline

$)C<html><body>
<p><font size="2" face="sans-serif">. =EC69N &nbsp;4T<br>
</font><font size="2" face="sans-serif"><br>
</font><font size="2" face="sans-serif">IBM DeveloperConnect + play.node 2016?! &nbsp;Seoul?!<- GO4B 2016?y 11?y 23@O?! 5n7OGXAV<E<- 0(;gGU4O4Y. @L:%F. 5n7O@L ?O7a5G>z=@4O4Y. <br>
</font><font size="2" face="sans-serif"><br>
</font><font size="2" face="sans-serif">>F7! &nbsp;3;?k@; H.@NGXAV=C1b 9Y6x4O4Y. 88>`, 3;?k?! <vA$ ;gGW@L GJ?dGO0E3*, Az9.@L @V@8=C8i, hykoh@kr.ibm.com7N 8^@O@; AV=C1b 9Y6x4O4Y. <br>
</font><font size="2" face="sans-serif"><br>
</font><font size="2" face="sans-serif">5n7O@Z8m 	. =EC69N &nbsp;4T <br>
</font><font size="2" face="sans-serif"><br>
</font><font size="2" face="sans-serif">@e<R 		Ritz Carlton Hotel Seoul<br>
</font><font size="2" face="sans-serif">		<-?o=C 0-3218 :@@:;g7N 120<br>
</font><font size="2" face="sans-serif">		Seoul<br>
</font><font size="2" face="sans-serif">	<br>
</font><font size="2" face="sans-serif">3/B%		2016?y 11?y 23@O<br>
</font><font size="2" face="sans-serif"><br>
</font><font size="2" face="sans-serif">@L9x G`;g?!<- :I <v @V1f 9Y6x4O4Y. <br>
</font><font size="2" face="sans-serif"><br>
</font><font size="2" face="sans-serif"><br>
</font><font size="2" face="sans-serif">IBM</font></body></html>
--0__=0ABB0AF7DF8452638f9e8a93df938690918c0ABB0AF7DF845263--

`

**Comment by outsideris** [comment]
안녕하세요. 대답이 늦어서 죄송합니다. 위 부분은 IBM 쪽에 확인했는데 시스템에서 Euc-kr로 보내는데 클라이언트에서 처리가 안된것 같네요. 

메일은 등록 확인용 메일로 내용은 다음과 같습니다. 

```
IBM DeveloperConnect + play.node 2016에  Seoul에서 하는 2016월 11월 23일에 등록해주셔서 감사합니다. 이벤트 등록이 완료되었습니다. 

아래  내용을 확인해주시기 바랍니다. 만약, 내용에 수정 사항이 필요하거나, 질문이 있으시면, hykoh@kr.ibm.com로 메일을 주시기 바랍니다. 

등록자명 OOO님 

장소 Ritz Carlton Hotel Seoul
서울시 강남구 봉은사로 120
Seoul

날짜  2016월 11월 23일

이번 행사에서 뵐 수 있길 바랍니다. 
```
