### ISSUE TITLE
Get your ticket 버튼이 살짝 짤리네요.

### ISSUE THREAD

**Issue by meoooh** [playnodeconf/ama#13]
![image](https://cloud.githubusercontent.com/assets/3191533/20048337/423bd476-a4ff-11e6-94a3-18c4c0a22d6b.png)
![image](https://cloud.githubusercontent.com/assets/3191533/20048351/538e672a-a4ff-11e6-9fae-3d4e0f967617.png)

section#breadcrumb 의 높이를 조정하니까 온전히 보이긴 하는거 같은데....

**Comment by outsideris** [comment]
제보해 주셔서 감사합니다. 처리가 약간 늦었네요 수정했습니다.
혹시 다시 발생하면 얘기해 주세요.
