### ISSUE TITLE
playnode track D 에 자리가 남아있나요 ,..?

### ISSUE THREAD

**Issue by sanguneo** [playnodeconf/ama#14]
플레이노드 기다리던 개발자인데요,.

온오프믹스에도 안뜨길래 우여니 들어와봤는데 듣고싶은 세션이 있어서 문의드려요,
IBM 디벨로퍼 커넥트 참석하면 지금 플레이노드 D트랙 탐석이 가능할까요 ..?

**Comment by outsideris** [comment]
안녕하세요. 기다려주셔서 감사합니다. 
평소에는 온오프믹스를 이용했지만 이번에는 IBM 디벨로퍼 커넥트와 함께 한 관계로 IBM의 등록을 이용하게 되었습니다. 참가 신청을 받을 때 사용자의 선호도를 받기는 했지만 IBM 트랙과 저희 트랙의 참석자를 구분하고 있지는 않습니다.
IBM 디벨로퍼 커넥트에 참가하시면 플레이노드 세션도 참가할 수 있습니다.

다만 신청자의 선호도에서 플레이노드쪽 참석자가 많을 것으로 예상되어 저희쪽 신청은 닫은 상태로 IBM 쪽에서만 신청을 받고 있습니다. 트랙에 참석자가 많을 수 있으므로 좋은 자리에서 참석을 하고 싶으시면 일찍 오셔서 자리를 잡기를 권해드립니다.
