### ISSUE TITLE
2016 playnode 행사에 주차지원 되나요?

### ISSUE THREAD

**Issue by behumble** [playnodeconf/ama#16]
여기에 질문하는게 적절한지 걱정입니다 :)
내일 리츠칼튼에서 행사인데 주차지원이나 할인이 있는지요?

**Comment by outsideris** [comment]
행사전날 바빠서 답변을 못드려서 죄송합니다. ㅠ

**Comment by behumble** [comment]
주차지원 빵빵하더라구요. 감사합니다.
