### ISSUE TITLE
등록 시간이 아닌 오후에 등록해도 되나요?

### ISSUE THREAD

**Issue by hazebob** [playnodeconf/ama#17]
등록 시간이 아닌 오후에 등록해도 되나요?

**Comment by outsideris** [comment]
어제는 행사를 진행할 시간이 없어서 답변을 못드렸네요. 오후에도 등록을 받은 걸로 알고 있는데 잘 참석하셨는지 모르겠습니다. ㅠ

**Comment by hazebob** [comment]
등록 가능하더군요. 참석 잘 했습니다 :-)
