### ISSUE TITLE
2017년에도 play.node 컨퍼런스 계획이 있는지 궁금합니다.

### ISSUE THREAD

**Issue by hamdoe** [playnodeconf/ama#18]
안녕하세요!

올해에도 play.node 컨퍼런스가 개최되는지, 시기는 언제쯤일지 알고 싶습니다.

개발 관련 컨퍼런스를 찾다가 발견했는데, 문의처가 여기밖에 없어 질문 남깁니다.

**Comment by outsideris** [comment]
지속적으로 하려고 작년에도 추진한 것이긴 한데 운영진들도 본업이 있어서 올해도 진행되어 봐야 알 것 같습니다.
아직은 구체적으로 논의되지 않았습니다. 페이스북이나 트위터 등을 팔로우 하시면 진행될 때 내용을 보실 수 있으실 겁니다.

**Comment by hamdoe** [comment]
답변 감사합니다. 소식 기대하고 있겠습니다! ^^
