### ISSUE TITLE
call for paper

### ISSUE THREAD

**Issue by imjuni** [playnodeconf/ama#2]
그리 자신은 없지만, call for paper에 응모를 하려고 했는데 404 오류가 나네요. 이 경우 어떻게 해야 하나요?

**Comment by daclouds** [comment]
@imjuni call for paper 가 뭔가요? 'ㅁ' Call for Speakers 말씀하신 건가요? 
아예 팝업이 안뜬다는 건가요? 아니면 완료가 안된다는 건가요? 
접속 환경은 PC 인가요? 아니면 모바일로 접속하셨나요?
좀 더 자세한 설명이 필요할 것 같습니다. (URL 알려주시면 더 좋구요~ )

관심 가져주셔서 고맙습니다~

**Comment by imjuni** [comment]
call for speakers 이네요, 논문을 제출하는 것과 혼동이 있었습니다. submit form 까지 정상적으로 되고, 5개의 질문을 답하고 나서 submit 하면 git 404 페이지로 리디렉션 됩니다

**Comment by daclouds** [comment]
@imjuni 접속 환경을 알려주실 수 있나요?
PC 인지 모바일인지
OS 는 무엇인지
브라우저는 어떤걸 사용했는지
...

(지금 제가 했을 땐 잘 되서.. 아무래도 환경 문제인 것 같아서요; )

아니면 내용을 적어서 playnodeconf@gmail.com 으로 보내주셔도 됩니다.

불편을 드려 죄송합니다.
그리고 지원해 주셔서 고맙습니다~ ^^

**Comment by imjuni** [comment]
pc 환경에서 접속했고 브라우저는 크롬입니다. 다만 pc 중에서도 맥프레 에서 접속했고 크롬은 자동 업데이트로 최신버전 유지중입니다.

**Comment by daclouds** [comment]
@imjuni 동일한 환경에서 테스트 해보았으나 재현이 되지 않네요; 
다른 장비에서 다시 시도해보시거나(스마트폰에서도 잘 되요~ ) 메일로 보내주시기 바랍니다.

고맙습니다.

**Comment by insanehong** [comment]
가끔 크롬 익스텐션등으로 충돌이나서 js 오동작같은 문제가 발생할수도 있을거 같습니다. 
@daclouds 님 말씀처럼 다른 기기에서 시도해보시고 안된다면  playnodeconf@gmail.com 로 신청해주시면 반영하도록 하겠습니다.
