### ISSUE TITLE
혹시 스폰이 가능한 행사인가요?

### ISSUE THREAD

**Issue by kimjmin** [playnodeconf/ama#3]
안녕하세요.
혹시 회사 스폰이 가능한 행사인지 여쭙고 싶습니다. :)

**Comment by insanehong** [comment]
넵 스폰서 모집중입니다. 연락가능한 이메일과 관련정보를

 playnodeconf@gmail.com 메일로 알려 주시면

스폰서 관련 정보를 메일로 발송해드리겠습니다.

감사합니다.

2015-10-14 12:37 GMT+09:00 Jongmin Kim notifications@github.com:

> 안녕하세요.
> 혹시 회사 스폰이 가능한 행사인지 여쭙고 싶습니다. :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/playnodeconf/ama/issues/3.

## 

/*
- @insanehong
  *
- @Name DeokHong Kim
- @Desc Web Developer, Front-end Engineer at NAVER Corp.
- @Twitter @insanehong http://twitter.com/insanehong
- @Blog incorrect note http://insanehong.kr/
- @Return insanehong@gmail.com
- @Aboutme : http://about.me/insanehong
  */

**Comment by outsideris** [comment]
네 회사 스폰 가능합니다. 현재 모집중에 있습니다. 상세한 내용을 홈페이지에 게시할 예정인데(늦어서 죄송합니다.) 상세 내용이 궁금하시면 말씀해 주세요.

**Comment by kimjmin** [comment]
감사합니다. 메일 보내드렸습니다. :)

**Comment by insanehong** [comment]
play.node 2015 스폰서 모집을 마감합니다.
