### ISSUE TITLE
플레이노드 컨퍼런스 참가 비용 고용보험 적용 문의

### ISSUE THREAD

**Issue by kyeonghopark** [playnodeconf/ama#5]
플레이노드 컨퍼런스 참가 비용 고용보험 적용되나요?

**Comment by insanehong** [comment]
고용보험은 구체적으로 어떤것을 얘기하시는지 알려주시면 좋을거 같습니다.

**Comment by insanehong** [comment]
행사가 끝난관계로 닫습니다. 이슈가 있으면 다시 열고 댓글 남겨주세요
