### ISSUE TITLE
초대관련해서 문의드립니다.

### ISSUE THREAD

**Issue by wormslab** [playnodeconf/ama#6]
안녕하세요.

스피커를통해서 초대 받았는데요.
별다른 수신메일이 오지않아서 잘 초대가 된건지 궁금합니다.

어떻게 확인해야 할까요?

**Comment by insanehong** [comment]
안녕하세요. 

금주내로 참가안내 메일을 발송예정에 있습니다. 

조금만 기다려주시면 참가관련 안내를 받으실수 있으실 거에요^^

**Comment by wormslab** [comment]
감사합니다!!
