### ISSUE TITLE
어제 진행된 playnode 컨퍼런스 녹화 자료 구할 수 없을까요? 

### ISSUE THREAD

**Issue by ghost** [playnodeconf/ama#8]
참여신청 다하고, 손꼽아 기다리고 있었는데,
토요일에 하는 줄 알고 있었어요.
어제 끝났다는 것을 오늘 새벽에 알고서는, 
지불한 참가비보다 
소중한 강의에 참여 못한게 더 속상하고
분해서 자책하고 또 자책하고 있습니다.

혹시라도, 녹화 영상이 있으시다면 E-mail로 보내 주실 수 있으신가요?ㅠㅠ
부탁드립니다. 1달을 기다리고 기다렸었는데 
너무 괴롭습니다.

이름은 "유일환" 이고 ONOFFMIX에서 얼리버드로 참가신청 했었습니다.
만일 보내주시기가 어려우시다면, 
제가 직접 가서라도 강의 영상을 꼭 보고 싶습니다.
지금 이직 준비라서, 시간은 언제라도 괜찮고요.
간절히 부탁드립니다.

E-mail : oneinme@naver.com
name : 유일환

**Comment by insanehong** [comment]
현재 녹화자료 공개는 계획되어 있지 않습니다. 

죄송합니다.

**Comment by ghost** [comment]
네 .. 
꼭 듣고 싶었는데, 어쩔 수 없죠..
누군가, 요약문이라도 올려 주시길 기대할께요 ^^

귀한 모임 마련하느라 고생하셨습니다
그럼 안녕히계세요.
