### ISSUE TITLE
발표자료 언제 올라오나요?

### ISSUE THREAD

**Issue by asrada2001** [playnodeconf/ama#9]
행사 마감할 때 스텝분한테 문의 했는데요,
발표자료는 홈페이지에 올려주실 예정이라고 들었는데 언제쯤 올라올까요?
일부 연사분들은 PPT 다운로드 경로를 적어주셔서 다운받을 수 있었는데 그렇지 않은 분들도 계셨거든요.
녹화본은 예정에 없다고 하시니 발표자료 만이라도 올려주시면 좋겠습니다.

**Comment by daclouds** [comment]
You can find presentation in playnode.io website.

Refer to the link below
http://playnode.io/#schedule
